## Fetch API

## Arrivals :

In [3]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

base_url = os.getenv("BASE_URL")   # t.ex. https://api.swedavia.se/flightinfo/v2
api_key = os.getenv("FLIGHT_KEY")

url = f"{base_url}/ARN/arrivals/2026-10-13"
headers = {
    "Ocp-Apim-Subscription-Key": api_key,
    "Accept": "application/json",
}

response = requests.get(url, headers=headers, timeout=10)
response.raise_for_status()
data = response.json()
df = pd.json_normalize(data["flights"])
print(df.head())

  flightId departureAirportSwedish departureAirportEnglish codeShareData  \
0   W45189                  Tirana                  Tirana            []
1   W62407                Budapest                Budapest            []
2   FR4464              Birmingham              Birmingham            []
3   FR3008                  Dublin                  Dublin            []
4   FR7686                Brindisi                Brindisi            []

  remarksEnglish remarksSwedish viaDestinations diIndicator  \
0             []             []              []           I
1             []             []              []           S
2             []             []              []           I
3             []             []              []           I
4             []             []              []           S

  airlineOperator.iata airlineOperator.icao  ...  \
0                   W4                  WMT  ...
1                   W6                  WZZ  ...
2                   FR                  RYR  ...
3                   FR                  RYR  ...
4                   FR                  RYR  ...

  flightLegIdentifier.departureAirportIcao  \
0                                     LATI
1                                     LHBP
2                                     EGBB
3                                     EIDW
4                                     LIBR

  flightLegIdentifier.arrivalAirportIcao baggage.baggageClaimUnit  \
0                                   ESSA                      NaN
1                                   ESSA                      NaN
2                                   ESSA                      NaN
3                                   ESSA                      NaN
4                                   ESSA                      NaN

  flightLegIdentifier.aircraftRegistration arrivalTime.estimatedUtc  \
0                                      NaN                      NaN
1                                      NaN                      NaN
2                                      NaN                      NaN
3                                      NaN                      NaN
4                                      NaN                      NaN

  arrivalTime.actualUtc locationAndStatus.gate baggage.firstBagUtc  \
0                   NaN                    NaN                 NaN
1                   NaN                    NaN                 NaN
2                   NaN                    NaN                 NaN
3                   NaN                    NaN                 NaN
4                   NaN                    NaN                 NaN

  baggage.lastBagUtc flightLegIdentifier.ssrCode
0                NaN                         NaN
1                NaN                         NaN
2                NaN                         NaN
3                NaN                         NaN
4                NaN                         NaN

[5 rows x 31 columns]

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   flightId                                    249 non-null    str
 1   departureAirportSwedish                     249 non-null    str
 2   departureAirportEnglish                     249 non-null    str
 3   codeShareData                               249 non-null    object
 4   remarksEnglish                              249 non-null    object
 5   remarksSwedish                              249 non-null    object
 6   viaDestinations                             249 non-null    object
 7   diIndicator                                 249 non-null    str
 8   airlineOperator.iata                        249 non-null    str
 9   airlineOperator.icao                        249 non-null    str
 10  airlineOperator.name                        249 non-null    str
 11  arrivalTime.scheduledUtc                    249 non-null    str
 12  locationAndStatus.terminal                  249 non-null    str
 13  locationAndStatus.flightLegStatus           249 non-null    str
 14  locationAndStatus.flightLegStatusSwedish    249 non-null    str
 15  locationAndStatus.flightLegStatusEnglish    249 non-null    str
 16  flightLegIdentifier.callsign                249 non-null    str
 17  flightLegIdentifier.flightId                249 non-null    str
 18  flightLegIdentifier.flightDepartureDateUtc  249 non-null    str
 19  flightLegIdentifier.departureAirportIata    249 non-null    str
 20  flightLegIdentifier.arrivalAirportIata      249 non-null    str
 21  flightLegIdentifier.departureAirportIcao    249 non-null    str
 22  flightLegIdentifier.arrivalAirportIcao      249 non-null    str
 23  baggage.baggageClaimUnit                    207 non-null    str
 24  arrivalTime.estimatedUtc                    204 non-null    str
 25  arrivalTime.actualUtc                       202 non-null    str
 26  locationAndStatus.gate                      202 non-null    str
 27  baggage.firstBagUtc                         202 non-null    str
 28  baggage.lastBagUtc                          201 non-null    str
 29  flightLegIdentifier.aircraftRegistration    204 non-null    str
 30  flightLegIdentifier.ssrCode                 204 non-null    str
dtypes: object(4), str(27)
memory usage: 111.8+ KB

In [ ]:
df.isnull()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
244,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
245,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
246,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
247,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
248,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.head()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.departureAirportIcao,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.aircraftRegistration,flightLegIdentifier.ssrCode
0,EW4607,Stuttgart,Stuttgart,[],[],[],[],S,EW,EWG,...,EDDS,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,W45189,Tirana,Tirana,[],[],[],[],I,W4,WMT,...,LATI,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,W62403,Budapest,Budapest,[],[],[],[],S,W6,WZZ,...,LHBP,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,EW4348,Salzburg,Salzburg,[],[],[],[],S,EW,EWG,...,LOWS,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR2234,Wroclaw,Wroclaw,[],[],[],[],S,FR,RYR,...,EPWR,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['flightId', 'departureAirportSwedish', 'departureAirportEnglish',
       'codeShareData', 'remarksEnglish', 'remarksSwedish', 'viaDestinations',
       'diIndicator', 'airlineOperator.iata', 'airlineOperator.icao',
       'airlineOperator.name', 'arrivalTime.scheduledUtc',
       'locationAndStatus.terminal', 'locationAndStatus.flightLegStatus',
       'locationAndStatus.flightLegStatusSwedish',
       'locationAndStatus.flightLegStatusEnglish',
       'flightLegIdentifier.callsign', 'flightLegIdentifier.flightId',
       'flightLegIdentifier.flightDepartureDateUtc',
       'flightLegIdentifier.departureAirportIata',
       'flightLegIdentifier.arrivalAirportIata',
       'flightLegIdentifier.departureAirportIcao',
       'flightLegIdentifier.arrivalAirportIcao', 'baggage.baggageClaimUnit',
       'arrivalTime.estimatedUtc', 'arrivalTime.actualUtc',
       'locationAndStatus.gate', 'baggage.firstBagUtc', 'baggage.lastBagUtc',
       'flightLegIdentifier.aircraftRegistration',
       'flightLegIdentifier.ssrCode'],
      dtype='str')

In [ ]:
df.dtypes

flightId                                         str
departureAirportSwedish                          str
departureAirportEnglish                          str
codeShareData                                 object
remarksEnglish                                object
remarksSwedish                                object
viaDestinations                               object
diIndicator                                      str
airlineOperator.iata                             str
airlineOperator.icao                             str
airlineOperator.name                             str
arrivalTime.scheduledUtc                         str
locationAndStatus.terminal                       str
locationAndStatus.flightLegStatus                str
locationAndStatus.flightLegStatusSwedish         str
locationAndStatus.flightLegStatusEnglish         str
flightLegIdentifier.callsign                     str
flightLegIdentifier.flightId                     str
flightLegIdentifier.flightDepartureDateUtc       str
flightLegIdentifier.departureAirportIata         str
flightLegIdentifier.arrivalAirportIata           str
flightLegIdentifier.departureAirportIcao         str
flightLegIdentifier.arrivalAirportIcao           str
baggage.baggageClaimUnit                         str
arrivalTime.estimatedUtc                         str
arrivalTime.actualUtc                            str
locationAndStatus.gate                           str
baggage.firstBagUtc                              str
baggage.lastBagUtc                               str
flightLegIdentifier.aircraftRegistration         str
flightLegIdentifier.ssrCode                      str
dtype: object

In [ ]:
df['locationAndStatus.flightLegStatus'].value_counts()

locationAndStatus.flightLegStatus
LAN    202
DEL     45
CAN      2
Name: count, dtype: int64

In [ ]:
df['locationAndStatus.flightLegStatusEnglish'].value_counts()

locationAndStatus.flightLegStatusEnglish
Deleted         45
Cancelled        2
Landed 02:34     1
Landed 02:54     1
Landed 03:51     1
                ..
Landed 23:06     1
Landed 14:50     1
Landed 11:06     1
Landed 10:31     1
Landed 22:11     1
Name: count, Length: 204, dtype: int64

In [ ]:
df['locationAndStatus.flightLegStatusSwedish'].value_counts()

locationAndStatus.flightLegStatusSwedish
Borttagen       45
Inställd         2
Landat 02:34     1
Landat 02:54     1
Landat 03:51     1
                ..
Landat 23:06     1
Landat 14:50     1
Landat 11:06     1
Landat 10:31     1
Landat 22:11     1
Name: count, Length: 204, dtype: int64

## Function for airports (svedavia) & Dates as Parameters

In [ ]:
# 1. Get BASE_URL & API KEY from dotenv file 
BASE_URL = os.getenv("BASE_URL")
API_KEY = os.getenv("FLIGHT_KEY")

In [ ]:
# 2. Create an array with the Svedavia Airports 
SWE_AIRPORTS = {
    "ARN": "Stockholm Arlanda Airport",
    "BMA": "Bromma Stockholm Airport",
    "GOT": "Göteborg Landvetter Airport",
    "MMX": "Malmö Airport",
    "LLA": "Luleå Airport",
    "UME": "Umeå Airport",
    "OSD": "Åre Östersund Airport",
    "VBY": "Visby Airport",
    "RNB": "Ronneby Airport",
    "KRN": "Kiruna Airport",
}

**Source used:** https://www.geeksforgeeks.org/python/get-yesterdays-date-using-python/

In [ ]:
# 3. Create a parameter for the dates to fetch 

# Import date and timedelta class
# from datetime module
from datetime import date
from datetime import timedelta

# Array with the days [today -1, today-2, today-3] 
DATES = [date.today(), date.today() - timedelta(days=1), date.today() -
         timedelta(days=2)]

#print the first day in the array (yesterday)
print(DATES[0])


# print all the dates 
for date in DATES:
    print(date)

2026-10-11
2026-10-11
2026-10-10
2026-10-09

In [ ]:
# 5. Create a header - request - response 
# 6. Loop 
# For each AIRPORT 
# For each DATE

def get_flight_data(direction):
    # Empty list to store the flights in 
    all_flights = []

    headers = {
        "Ocp-Apim-Subscription-Key": API_KEY,
        "Accept": "application/json",
    }
    for airport in SWE_AIRPORTS: 
        for date in DATES: 
            url = f"{BASE_URL}/{airport}/{direction}/{date}"
            response = requests.get(url, headers=headers)
            response.raise_for_status()
            for flight in response.json()["flights"]:
                all_flights.append({**flight, "Swedavia_airport_name": airport, "Date_fetched": str(date)}) # adderade datum för det hämtade datumet också för att få in det i DF 
    return all_flights

In [ ]:
# 7. Print results 

df_arrivals = pd.json_normalize(get_flight_data("arrivals"), sep="_")

In [ ]:
df_departures = pd.json_normalize(get_flight_data("departures"), sep="_")

In [ ]:
df_arrivals

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,Swedavia_airport_name,Date_fetched,...,flightLegIdentifier_arrivalAirportIcao,baggage_baggageClaimUnit,arrivalTime_estimatedUtc,arrivalTime_actualUtc,locationAndStatus_gate,baggage_firstBagUtc,baggage_lastBagUtc,flightLegIdentifier_aircraftRegistration,flightLegIdentifier_ssrCode,baggage_estimatedFirstBagUtc
0,EW2212,Stuttgart,Stuttgart,[],[],[],[],S,ARN,2026-10-11,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TO7440,Paris ORY,Paris ORY,[],[],[],[],S,ARN,2026-10-11,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR4464,Birmingham,Birmingham,[],[],[],[],I,ARN,2026-10-11,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR3008,Dublin,Dublin,[],[],[],[],I,ARN,2026-10-11,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR4538,Rhodos,Rhodes,[],[],[],[],S,ARN,2026-10-11,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1353,SK1040,Stockholm ARN,Stockholm ARN,[],"[{'text': 'Landed 09:06', 'indicator': 'NEUTRA...","[{'text': 'Landat 09:06', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-11,...,ESNQ,1,2026-10-11T07:00:00Z,2026-10-11T07:06:00Z,01,2026-10-11T07:20:24Z,2026-10-11T07:28:43Z,SEROB,NaN,NaN
1354,SK1044,Stockholm ARN,Stockholm ARN,"[EY3911, KL8502]","[{'text': 'Landed 17:51', 'indicator': 'NEUTRA...","[{'text': 'Landat 17:51', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-11,...,ESNQ,1,2026-10-11T15:53:00Z,2026-10-11T15:51:00Z,01,2026-10-11T16:07:06Z,2026-10-11T16:14:22Z,SEROB,NaN,NaN
1355,SK1042,Stockholm ARN,Stockholm ARN,"[AF4551, BT6158, EY3979, KL8500, NH6338]","[{'text': 'Landed 16:10', 'indicator': 'NEUTRA...","[{'text': 'Landat 16:10', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-11,...,ESNQ,1,2026-10-11T14:05:00Z,2026-10-11T14:10:00Z,01,2026-10-11T14:26:05Z,2026-10-11T14:34:20Z,SERZX,NaN,NaN
1356,SK1042,Stockholm ARN,Stockholm ARN,"[EY3913, KL8500, LO5407]","[{'text': 'Landed 13:30', 'indicator': 'NEUTRA...","[{'text': 'Landat 13:30', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-09,...,ESNQ,1,2026-10-09T11:26:00Z,2026-10-09T11:30:00Z,01,2026-10-09T11:40:47Z,2026-10-09T11:49:54Z,LNRGN,NaN,NaN
1357,SK1044,Stockholm ARN,Stockholm ARN,"[EY3911, KL8502]","[{'text': 'Landed 20:34', 'indicator': 'NEUTRA...","[{'text': 'Landat 20:34', 'indicator': 'NEUTRA...",[],D,KRN,2026-10-09,...,ESNQ,1,2026-10-09T18:33:00Z,2026-10-09T18:34:00Z,01,2026-10-11T07:20:23Z,NaN,SEROU,NaN,NaN

In [ ]:
df_departures

,flightId,arrivalAirportSwedish,arrivalAirportEnglish,codeShareData,viaDestinations,remarksEnglish,remarksSwedish,diIndicator,Swedavia_airport_name,Date_fetched,...,locationAndStatus_gateActionSwedish,locationAndStatus_gateActionEnglish,locationAndStatus_gateOpenUtc,locationAndStatus_gateCloseUtc,checkIn_checkInStatus,checkIn_checkInStatusSwedish,checkIn_checkInStatusEnglish,flightLegIdentifier_aircraftRegistration,flightLegIdentifier_ssrCode,departureTime_estimatedUtc
0,EW2213,Stuttgart,Stuttgart,[],[],[],[],S,ARN,2026-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TO7441,Paris ORY,Paris ORY,[],[],[],[],S,ARN,2026-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FR4465,Birmingham,Birmingham,[],[],[],[],I,ARN,2026-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,FR3009,Dublin,Dublin,[],[],[],[],I,ARN,2026-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,FR970,Zadar,Zadar,[],[],[],[],S,ARN,2026-10-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1341,SK1041,Stockholm ARN,Stockholm ARN,"[AF4599, BT6193, EY3990, KL8483]",[],"[{'text': 'Departed 09:53', 'indicator': 'NEUT...","[{'text': 'Startat 09:53', 'indicator': 'NEUTR...",D,KRN,2026-10-11,...,Utgång stängd,Gate closed,2026-10-11T07:16:59Z,2026-10-11T07:33:00Z,C,Stängd,Closed,SEROB,NaN,NaN
1342,SK1045,Stockholm ARN,Stockholm ARN,"[BT6195, LO5438]",[],"[{'text': 'Departed 16:57', 'indicator': 'NEUT...","[{'text': 'Startat 16:57', 'indicator': 'NEUTR...",D,KRN,2026-10-11,...,Utgång stängd,Gate closed,2026-10-11T14:21:47Z,2026-10-11T14:37:45Z,C,Stängd,Closed,SERZX,NaN,NaN
1343,SK1047,Stockholm ARN,Stockholm ARN,[KL8485],[],"[{'text': 'Departed 18:33', 'indicator': 'NEUT...","[{'text': 'Startat 18:33', 'indicator': 'NEUTR...",D,KRN,2026-10-11,...,Utgång stängd,Gate closed,2026-10-11T15:50:12Z,2026-10-11T16:17:07Z,C,Stängd,Closed,SEROB,NaN,2026-10-11T16:30:00Z
1344,SK1045,Stockholm ARN,Stockholm ARN,"[AF4892, BT6195, EY3989, KL8485, LO5438]",[],"[{'text': 'Departed 14:19', 'indicator': 'NEUT...","[{'text': 'Startat 14:19', 'indicator': 'NEUTR...",D,KRN,2026-10-09,...,Utgång stängd,Gate closed,2026-10-09T11:16:22Z,2026-10-09T12:02:11Z,C,Stängd,Closed,LNRGN,NaN,2026-10-09T11:55:00Z
1345,SK1047,Stockholm ARN,Stockholm ARN,[],[],"[{'text': 'Departed 21:26', 'indicator': 'NEUT...","[{'text': 'Startat 21:26', 'indicator': 'NEUTR...",D,KRN,2026-10-09,...,Utgång stängd,Gate closed,2026-10-09T18:39:54Z,2026-10-09T18:58:04Z,C,Stängd,Closed,SEROU,NaN,NaN

## Summary: flight status (arrivals)

- Each flight can have 0, 1, or 2 messages (remarks): one regarding flight status, one regarding baggage.
- Status messages: Landed, Arrives, Estimated, Cancelled, Approach.
- Each message has a tag: NEUTRAL or NEGATIVE.
- NEGATIVE = 11 cancelled flights + 9 flights with a new time (Arrives/Estimated). These 9 are likely delayed but this has not yet been verified.
- There is no "Delayed" message for arrivals.
- Numbers above are from data fetched 11 Oct and will vary slightly, since the API returns live data.
- Remaining tasks: compare the 9 flights with their scheduled times; do the same for departures.

In [ ]:
# Only keep flights with at least one message
df_remarks = df_arrivals[df_arrivals["remarksEnglish"].str.len() > 0]

In [ ]:
len(df_remarks)

1149

In [ ]:
df_remarks["remarksEnglish"].head()

48    [{'text': 'Landed 23:38', 'indicator': 'NEUTRA...
49    [{'text': 'Landed 00:21', 'indicator': 'NEUTRA...
50    [{'text': 'Landed 00:23', 'indicator': 'NEUTRA...
51    [{'text': 'Landed 00:29', 'indicator': 'NEUTRA...
52    [{'text': 'Landed 01:02', 'indicator': 'NEUTRA...
Name: remarksEnglish, dtype: object

In [ ]:
# How many rows include messages? (0, 1 or 2 per flight)
df_arrivals["remarksEnglish"].str.len().value_counts()

remarksEnglish
2    1034
0     209
1     115
Name: count, dtype: int64

In [ ]:
df_exploded = df_remarks.explode("remarksEnglish")

In [ ]:
len(df_exploded)

2183

In [ ]:
df_exploded["remarksEnglish"].iloc[0]

{'text': 'Landed 23:38', 'indicator': 'NEUTRAL'}

In [ ]:
# Divide message into two columns: text and indicator
remarks_split = df_exploded["remarksEnglish"].apply(pd.Series)

In [ ]:
remarks_split["indicator"].value_counts()

indicator
NEUTRAL     2159
NEGATIVE      24
Name: count, dtype: int64

In [ ]:
remarks_split["text"].str.split().str[0].value_counts()

text
Landed       1096
Last         1025
Arrives        35
Cancelled      12
First           9
Estimated       6
Name: count, dtype: int64

In [ ]:
# Which messages are NEGATIVE (bad news)
negative = remarks_split[remarks_split["indicator"] == "NEGATIVE"]
negative["text"].value_counts()

text
Cancelled          12
Arrives 00:21       1
Arrives 22:58       1
Arrives 23:12       1
Arrives 23:17       1
Estimated 23:38     1
Arrives 23:14       1
Estimated 00:15     1
Estimated 15:30     1
Estimated 00:16     1
Arrives 23:55       1
Arrives 23:39       1
Arrives 22:56       1
Name: count, dtype: int64

## Delay definition

Instead of relying on `remarksEnglish` text (there is no "Delayed" remark for arrivals), compute delay from the timestamps:

- `delay_minutes` = (`actualUtc`, else `estimatedUtc`) - `scheduledUtc`
- `is_delayed` = `delay_minutes` >= 15 (common industry threshold; adjustable in `DELAY_THRESHOLD_MIN`)
- Cancelled (`CAN`) and deleted (`DEL`) flights are flagged separately and have no delay value.
- Flights with no actual or estimated time yet have no delay value (`delay_minutes` is NaN).
- `flight_date` = scheduled time converted to Swedish local time. We use this for "delays by date" instead of `Date_fetched`, because `Date_fetched` is only the date we asked the API for.
- Duplicate flight legs (the same flight listed on two fetched dates, around midnight) are removed before analysis.

Departure column names are assumed to mirror arrivals (`departureTime_*`). The first cell checks this.

In [ ]:
# Check which time columns exist in each dataframe
for name, d in [("arrivals", df_arrivals), ("departures", df_departures)]:
    print(name, [c for c in d.columns if "Time" in c])

arrivals ['arrivalTime_scheduledUtc', 'arrivalTime_estimatedUtc', 'arrivalTime_actualUtc']
departures ['departureTime_scheduledUtc', 'departureTime_actualUtc', 'departureTime_estimatedUtc']

In [ ]:
DELAY_THRESHOLD_MIN = 15

def add_delay(df, time_prefix):
    # time_prefix: "arrivalTime" or "departureTime"
    out = df.copy()
    sched = pd.to_datetime(out[f"{time_prefix}_scheduledUtc"], utc=True)
    est = pd.to_datetime(out.get(f"{time_prefix}_estimatedUtc"), utc=True)
    act = pd.to_datetime(out.get(f"{time_prefix}_actualUtc"), utc=True)
    
    # Flight date = scheduled time in Swedish local time (not the date we fetched)
    # Scheduled time never changes, so a delayed flight stays on its planned day
    out["flight_date"] = sched.dt.tz_convert("Europe/Stockholm").dt.date

    out["delay_minutes"] = (act.fillna(est) - sched).dt.total_seconds() / 60
    status = out["locationAndStatus_flightLegStatus"]
    out["is_cancelled"] = status.eq("CAN")
    out["is_deleted"] = status.eq("DEL")
    out["has_time"] = out["delay_minutes"].notna()
    # empty delay_minutes gives False here, so filter on has_time before counting
    out["is_delayed"] = out["delay_minutes"] >= DELAY_THRESHOLD_MIN
    return out

arr = add_delay(df_arrivals, "arrivalTime")
dep = add_delay(df_departures, "departureTime")

In [ ]:
# Sanity check: how many flights can we classify, and what does the delay distribution look like?
for name, d in [("arrivals", arr), ("departures", dep)]:
    print(f"--- {name}: {len(d)} rows")
    print(d[["is_cancelled", "is_deleted", "has_time", "is_delayed"]].sum())
    print(d["delay_minutes"].describe())

--- arrivals: 1358 rows
is_cancelled      12
is_deleted       209
has_time        1147
is_delayed       145
dtype: int64
count    1147.000000
mean        0.908646
std        41.967049
min       -63.950000
25%       -13.000000
50%        -5.783333
75%         4.200000
max       778.000000
Name: delay_minutes, dtype: float64
--- departures: 1346 rows
is_cancelled      12
is_deleted       211
has_time        1120
is_delayed       202
dtype: int64
count    1120.000000
mean        7.468676
std        31.282938
min       -20.000000
25%        -3.908333
50%         1.550000
75%         9.762500
max       418.000000
Name: delay_minutes, dtype: float64

In [ ]:
# Cross-check against the remarks: the 9 NEGATIVE "Arrives/Estimated" arrivals, are they >= 15 min late?
neg_new_time = arr[arr["remarksEnglish"].apply(
    lambda r: any(m["indicator"] == "NEGATIVE" and m["text"].split()[0] in ("Arrives", "Estimated") for m in r)
)]
neg_new_time[["flightId", "Swedavia_airport_name", "arrivalTime_scheduledUtc", "arrivalTime_estimatedUtc",
              "arrivalTime_actualUtc", "delay_minutes", "is_delayed"]]

,flightId,Swedavia_airport_name,arrivalTime_scheduledUtc,arrivalTime_estimatedUtc,arrivalTime_actualUtc,delay_minutes,is_delayed
288,D84324,ARN,2026-10-11T21:55:00Z,2026-10-11T22:21:00Z,NaN,26.000000,True
327,FR1110,ARN,2026-10-11T20:35:00Z,2026-10-11T20:58:30Z,NaN,23.500000,True
328,SK2566,ARN,2026-10-11T20:45:00Z,2026-10-11T21:12:30Z,NaN,27.500000,True
332,KL1227,ARN,2026-10-11T20:55:00Z,2026-10-11T21:17:30Z,NaN,22.500000,True
333,SK1488,ARN,2026-10-11T21:05:00Z,2026-10-11T21:38:00Z,NaN,33.000000,True
556,SK2472,ARN,2026-10-10T14:25:00Z,2026-10-10T21:17:30Z,2026-10-10T21:17:47Z,412.783333,True
889,SK096,ARN,2026-10-09T15:40:00Z,2026-10-09T22:27:30Z,2026-10-09T22:26:26Z,406.433333,True
1015,SK7846,GOT,2026-10-11T00:30:00Z,2026-10-11T13:28:00Z,2026-10-11T13:28:00Z,778.000000,True
1043,SK448,GOT,2026-10-11T21:55:00Z,2026-10-11T22:16:00Z,NaN,21.000000,True
1048,LH820,GOT,2026-10-11T21:25:00Z,2026-10-11T21:55:00Z,NaN,30.000000,True
1251,D84047,LLA,2026-10-11T21:15:00Z,2026-10-11T21:39:00Z,NaN,24.000000,True
1342,SK095,VBY,2026-10-09T14:20:00Z,2026-10-09T20:56:00Z,2026-10-09T21:00:00Z,400.000000,True

In [ ]:
# Do duplicate flights appear across fetched dates (same leg listed under two Date_fetched values)?
key = ["flightLegIdentifier_flightId", "flightLegIdentifier_flightDepartureDateUtc", "Swedavia_airport_name"]
print("BEFORE - arrivals dup legs:", arr.duplicated(key).sum(), "| departures dup legs:", dep.duplicated(key).sum())

# remove duplicates so each flight is counted only once
arr = arr.drop_duplicates(subset=key)
dep = dep.drop_duplicates(subset=key)

# NEW: check again, both should now be 0
print("AFTER  - arrivals dup legs:", arr.duplicated(key).sum(), "| departures dup legs:", dep.duplicated(key).sum())

BEFORE - arrivals dup legs: 3 | departures dup legs: 0
AFTER  - arrivals dup legs: 0 | departures dup legs: 0

In [ ]:
# Delay rate by airport, airline and date (arrivals; repeat for dep)
# only flights with a time that were NOT cancelled or deleted (10 cancelled/deleted flights still had a time and would otherwise be counted)
flown = arr[arr["has_time"] & ~arr["is_cancelled"] & ~arr["is_deleted"]]

by_airport = flown.groupby("Swedavia_airport_name")["is_delayed"].agg(["sum", "count", "mean"])
by_airline = flown.groupby("airlineOperator_name")["is_delayed"].agg(["sum", "count", "mean"]).sort_values("count", ascending=False)

# group by flight_date (Swedish local date) instead of Date_fetched
by_date = flown.groupby("flight_date")["is_delayed"].agg(["sum", "count", "mean"])

by_airport, by_airline.head(15), by_date

(                       sum  count      mean
 Swedavia_airport_name
 ARN                     88    785  0.112102
 BMA                      2     15  0.133333
 GOT                     25    188  0.132979
 KRN                      2      5  0.400000
 LLA                      6     39  0.153846
 MMX                      8     34  0.235294
 OSD                      1     11  0.090909
 RNB                      0      7  0.000000
 UME                      2     29  0.068966
 VBY                      6     22  0.272727,
                            sum  count      mean
 airlineOperator_name
 SAS Scandinavian Airlines   38    432  0.087963
 Norwegian                   26    182  0.142857
 Ryanair Ltd                 23    119  0.193277
 Finnair                      3     46  0.065217
 Lufthansa                    3     39  0.076923
 KLM                          7     28  0.250000
 Eurowings                    2     20  0.100000
 Wizz Air                     3     19  0.157895
 Nyxair                       3     18  0.166667
 Air France                   1     15  0.066667
 PopulAir                     0     14  0.000000
 FROST Air                    3     14  0.214286
 Austrian Airlines            0     13  0.000000
 Sunclass Airlines            7     13  0.538462
 Swiss                        0     13  0.000000,
              sum  count      mean
 flight_date
 2026-10-09    64    430  0.148837
 2026-10-10    28    281  0.099644
 2026-10-11    48    424  0.113208)

## Add column "fetched date" - alternative

In [5]:
from datetime import date

df["fetched_date"] = date.today()

df.head()

,flightId,departureAirportSwedish,departureAirportEnglish,codeShareData,remarksEnglish,remarksSwedish,viaDestinations,diIndicator,airlineOperator.iata,airlineOperator.icao,...,flightLegIdentifier.arrivalAirportIcao,baggage.baggageClaimUnit,flightLegIdentifier.aircraftRegistration,arrivalTime.estimatedUtc,arrivalTime.actualUtc,locationAndStatus.gate,baggage.firstBagUtc,baggage.lastBagUtc,flightLegIdentifier.ssrCode,fetched_date
0,W45189,Tirana,Tirana,[],[],[],[],I,W4,WMT,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-13
1,W62407,Budapest,Budapest,[],[],[],[],S,W6,WZZ,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-13
2,FR4464,Birmingham,Birmingham,[],[],[],[],I,FR,RYR,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-13
3,FR3008,Dublin,Dublin,[],[],[],[],I,FR,RYR,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-13
4,FR7686,Brindisi,Brindisi,[],[],[],[],S,FR,RYR,...,ESSA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-10-13